---
title: "Figure3_transeqtl_FDR0.05"
author: "Hao He"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
  toc: true
vignette: >
  %\VignetteIndexEntry{Figure3_transeqtl_FDR0.05}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,error = TRUE)
```

# Figure 3 Trans-eQTL at FDR 0.05 (5 Mb)
```{r Figure 3 Trans-eQTL at FDR 0.05 5Mb, message=FALSE, eval=TRUE,fig.height=16, fig.width=16}
library(sinaplot)
library(ggplot2)
library(plyr)
library(VennDiagram)
library(dplyr)
library(data.table)
library(qvalue)
library(gridExtra)
library(plotly)
library(reshape2)
library(MASS)
library(ggplot2)
library(viridis)
library(parallel)
library(cowplot)

a1 = a2 = a3 = n12 = n13 = n23 = n123 = list()
load("output/gene.anno.cis.RData")
#load eqtl pvalue for muga275
a <- get(load("output/muga275_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",as.integer(a$pos))
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", as.integer(a$pos))
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("output/gbrs275_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("output/fixed.muga275_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                             length(unique(b$genes)),
                             table(ab$trans_agree)[[1]],
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                             length(unique(c$genes)),
                             table(ac$trans_agree)[[1]],
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                             length(unique(c$genes)),
                             table(bc$trans_agree)[[1]],
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                             length(unique(b$genes)),
                             table(ab$trans_agree)[[1]],
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                             length(unique(c$genes)),
                             table(ac$trans_agree)[[1]],
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                             length(unique(c$genes)),
                             table(bc$trans_agree)[[1]],
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[1]] = length(unique(a$marker))
a2[[1]] = length(unique(b$marker))
a3[[1]] = length(unique(c$marker))
n12[[1]] <- length(unique(intersect(unique(a$marker), unique(b$marker))))
n13[[1]] <- length(unique(intersect(unique(a$marker), unique(c$marker))))
n23[[1]] <- length(unique(intersect(unique(b$marker), unique(c$marker))))
n123[[1]] = length(unique(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker)))))

#load eqtl pvalue for megamuga184
a <- get(load("output/megamuga184_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",as.integer(a$pos))
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", as.integer(a$pos))
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("output/gbrs184_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("output/fixed.megamuga184_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(b$genes)),
                              table(ab$trans_agree)[[1]],
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(c$genes)),
                              table(ac$trans_agree)[[1]],
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                              length(unique(c$genes)),
                              table(bc$trans_agree)[[1]],
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(b$genes)),
                              table(ab$trans_agree)[[1]],
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(c$genes)),
                              table(ac$trans_agree)[[1]],
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                              length(unique(c$genes)),
                              table(bc$trans_agree)[[1]],
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[2]] = length(unique(a$marker))
a2[[2]] = length(unique(b$marker))
a3[[2]] = length(unique(c$marker))
n12[[2]] <- length(unique(intersect(unique(a$marker), unique(b$marker))))
n13[[2]] <- length(unique(intersect(unique(a$marker), unique(c$marker))))
n23[[2]] <- length(unique(intersect(unique(b$marker), unique(c$marker))))
n123[[2]] = length(unique(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker)))))

#load eqtl pvalue for gigamuga358
a <- get(load("output/gigamuga358_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",as.integer(a$pos))
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", as.integer(a$pos))
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("output/gbrs358_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("output/fixed.gigamuga358_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(b$genes)),
                              table(ab$trans_agree)[[1]],
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(c$genes)),
                              table(ac$trans_agree)[[1]],
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                              length(unique(c$genes)),
                              table(bc$trans_agree)[[1]],
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(b$genes)),
                              table(ab$trans_agree)[[1]],
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)),
                              length(unique(c$genes)),
                              table(ac$trans_agree)[[1]],
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)),
                              length(unique(c$genes)),
                              table(bc$trans_agree)[[1]],
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2),
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[3]] = length(unique(a$marker))
a2[[3]] = length(unique(b$marker))
a3[[3]] = length(unique(c$marker))
n12[[3]] <- length(unique(intersect(unique(a$marker), unique(b$marker))))
n13[[3]] <- length(unique(intersect(unique(a$marker), unique(c$marker))))
n23[[3]] <- length(unique(intersect(unique(b$marker), unique(c$marker))))
n123[[3]] = length(unique(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker)))))

save(a1,a2,a3,n12, n13, n23, n123, file = "output/venn_diag_transeqtl_max.RData")

load("output/venn_diag_transeqtl_max.RData")
#bar plot
barplot(c(a3[[1]],a3[[2]],a3[[3]]),
        ylab = "Number of trans-eQTL at FDR 0.05",
        names.arg = c("FIXED.MUGA", "FIXED.MEGAMUGA", "FIXED.GIGAMUGA"), font.axis = 4, las = 1,cex.names=1.5,cex.lab = 1.5,
        col = c("cyan", "blue", "green3"),
        ylim = c(0,2500))

#MUGA
g1 <- draw.triple.venn(area1 = a1[[1]],
                 area2 = a2[[1]],
                 area3 = a3[[1]],
                 n12 = n12[[1]],
                 n23 = n23[[1]],
                 n13 = n13[[1]],
                 n123 = n123[[1]],
                 category = c("MUGA", "GBRS", "FIXED.MUGA"), lty = "blank",
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#MEGAMUGA
g2 <- draw.triple.venn(area1 = a1[[2]],
                 area2 = a2[[2]],
                 area3 = a3[[2]],
                 n12 = n12[[2]],
                 n23 = n23[[2]],
                 n13 = n13[[2]],
                 n123 = n123[[2]],
                 category = c("MEGAMUGA", "GBRS", "FIXED.MEGAMUGA"), lty = "blank",
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#GIGAMUGA
g3 <-  draw.triple.venn(area1 = a1[[3]],
                 area2 = a2[[3]],
                 area3 = a3[[3]],
                 n12 = n12[[3]],
                 n23 = n23[[3]],
                 n13 = n13[[3]],
                 n123 = n123[[3]],
                 category = c("GIGAMUGA", "GBRS", "FIXED.GIGAMUGA"), lty = "blank",
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#three venn diagrams
grid.arrange(gTree(children=g1),
             top=textGrob("Venn diagram for number of distal eQTLs (5Mb) between array and GBRS", gp=gpar(fontsize=26,font=8)))

grid.arrange(gTree(children=g2))

grid.arrange(gTree(children=g3))

```

# Figure 3 Scatterplot for Trans-eQTL at FDR 0.05 (5 Mb)
```{r Figure 3 Scatterplot for Trans-eQTL at FDR 0.05 5Mb, message=FALSE, eval=TRUE,fig.height=16, fig.width=16}
load("output/gene.anno.cis.RData")

######MUGA275######
#load eqtl pvalue for gbrs275
b <- get(load("output/gbrs275_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]
b_cutoff <- as.numeric(b[which.max(b$max_qvalue),"lod"])
b_cutoff

c <- get(load("output/fixed.muga275_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]
c_cutoff <- as.numeric(c[which.max(c$max_qvalue),"lod"])
c_cutoff

#get all the pair eqtl marker and gene from b and c
bc_pair <- rbind(b[,c("genes","eqtl_marker")],c[,c("genes","eqtl_marker")])
bc_pair$genes <- as.character(bc_pair$genes)
bc_pair <- bc_pair[!duplicated(bc_pair[,1:2]),]

#extract from b and c respectively
# load("output/gbrs275.eqtl.RData")
# bc_pair_b_lod <- bc_pair
# bc_pair_b_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_b_lod$g <- "GBRS"
load("output/bc_pair_b_lod_gbrs275.RData")

# load("output/fixed.muga275.eqtl.RData")
# bc_pair_c_lod <- bc_pair
# bc_pair_c_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_c_lod$g <- "FIXED.MUGA"
load("output/bc_pair_c_lod_fixed.muga275.RData")

bc_pair_lod1 <- merge(bc_pair_b_lod, bc_pair_c_lod, by = c("eqtl_marker", "genes"))
bc_pair_lod1$g <- ifelse(bc_pair_lod1$lod.x >= b_cutoff & bc_pair_lod1$lod.y >= c_cutoff, "Both", ifelse(bc_pair_lod1$lod.x >= b_cutoff & bc_pair_lod1$lod.y < c_cutoff,"GBRS","FIXED.MUGA"))
#scatter plot for the overlapped genes between GBRS and FIXED.MUGA
# scatter plot
plot_bcpair_lod1 <- plot_ly(bc_pair_lod1, x = ~lod.x) %>%
  add_markers(y = ~lod.y, text = bc_pair_lod1$eqtl_marker, name = "", showlegend = FALSE) %>%
  add_lines(y = ~fitted(loess(lod.y ~ lod.x)),
            line = list(color = 'black'),
            name = "", showlegend = FALSE) %>%
  add_lines(y = ~lod.x, color = I("red"), name = "", showlegend = FALSE) %>%
  layout(xaxis = list(title = 'LODs in GBRS'),
         yaxis = list(title = 'LODs in FIXED.MUGA'),
         title = paste0('Scatter plot of LODs for distal eQTLs in identified in either array or GBRS'))

plot_bcpair_lod1

# Get density of points in 2 dimensions.
# @param x A numeric vector.
# @param y A numeric vector.
# @param n Create a square n by n grid to compute density.
# @return The density within each square.
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

bc_pair_lod1$density <- get_density(bc_pair_lod1$lod.x, bc_pair_lod1$lod.y, n = 100)
plot_bcpair_lod21 <- ggplot(bc_pair_lod1) + 
  geom_point(aes(lod.x, lod.y, color = factor(bc_pair_lod1$g))) + 
  #scale_color_viridis() + 
  theme(aspect.ratio=1) +
  xlab("LODs in GBRS") +
  ylab("LOD in FIXED.MUGA") +
  ggtitle("Scatter plot of LODs for distal eQTLs in identified in either array or GBRS") + 
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(legend.title=element_blank(), text = element_text(size=22), 
        axis.title=element_text(size=22,face="bold")) +
  theme(plot.title = element_text(hjust=0.5, size = 28))

plot_bcpair_lod21


######MEGAMUGA184######
#load eqtl pvalue for gbrs184
b <- get(load("output/gbrs184_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]
b_cutoff <- as.numeric(b[which.max(b$max_qvalue),"lod"])
b_cutoff

c <- get(load("output/fixed.megamuga184_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]
c_cutoff <- as.numeric(c[which.max(c$max_qvalue),"lod"])
c_cutoff

#get all the pair eqtl marker and gene from b and c
bc_pair <- rbind(b[,c("genes","eqtl_marker")],c[,c("genes","eqtl_marker")])
bc_pair$genes <- as.character(bc_pair$genes)
bc_pair <- bc_pair[!duplicated(bc_pair[,1:2]),]

#extract from b and c respectively
# load("output/gbrs184.eqtl.RData")
# bc_pair_b_lod <- bc_pair
# bc_pair_b_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_b_lod$g <- "GBRS"
load("output/bc_pair_b_lod_gbrs184.RData")

# load("output/fixed.megamuga184.eqtl.RData")
# bc_pair_c_lod <- bc_pair
# bc_pair_c_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_c_lod$g <- "FIXED.MEGAMUGA"
load("output/bc_pair_c_lod_fixed.megamuga184.RData")

bc_pair_lod2 <- merge(bc_pair_b_lod, bc_pair_c_lod, by = c("eqtl_marker", "genes"))
bc_pair_lod2$g <- ifelse(bc_pair_lod2$lod.x >=b_cutoff & bc_pair_lod2$lod.y >= c_cutoff, "Both", ifelse(bc_pair_lod2$lod.x >= b_cutoff & bc_pair_lod2$lod.y < c_cutoff,"GBRS","FIXED.MEGAMUGA"))
#scatter plot for the overlapped genes between GBRS and FIXED.MEGAMUGA
# scatter plot
plot_bcpair_lod1 <- plot_ly(bc_pair_lod2, x = ~lod.x) %>%
  add_markers(y = ~lod.y, text = bc_pair_lod2$eqtl_marker, name = "", showlegend = FALSE) %>%
  add_lines(y = ~fitted(loess(lod.y ~ lod.x)),
            line = list(color = 'black'),
            name = "", showlegend = FALSE) %>%
  add_lines(y = ~lod.x, color = I("red"), name = "", showlegend = FALSE) %>%
  layout(xaxis = list(title = 'LODs in GBRS'),
         yaxis = list(title = 'LODs in FIXED.MEGAMUGA'),
         title = paste0('Scatter plot of LODs for distal eQTLs in identified in either array or GBRS'))

plot_bcpair_lod1


bc_pair_lod2$density <- get_density(bc_pair_lod2$lod.x, bc_pair_lod2$lod.y, n = 100)
plot_bcpair_lod22 <- ggplot(bc_pair_lod2) + 
  geom_point(aes(lod.x, lod.y, color = factor(bc_pair_lod2$g))) + 
  #scale_color_viridis() + 
  theme(aspect.ratio=1) +
  xlab("LODs in GBRS") +
  ylab("LOD in FIXED.MEGAMUGA") +
  ggtitle("Scatter plot of LODs for distal eQTLs in identified in either array or GBRS") + 
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(legend.title=element_blank(), text = element_text(size=22), 
        axis.title=element_text(size=22,face="bold")) +
  theme(plot.title = element_text(hjust=0.5, size = 28))

plot_bcpair_lod22

######GIGAMUGA358######
#load eqtl pvalue for gbrs358
b <- get(load("output/gbrs358_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",as.integer(b$pos))
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", as.integer(b$pos))
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]
b_cutoff <- as.numeric(b[which.max(b$max_qvalue),"lod"])
b_cutoff

c <- get(load("output/fixed.gigamuga358_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",as.integer(c$pos))
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", as.integer(c$pos))
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]
c_cutoff <- as.numeric(c[which.max(c$max_qvalue),"lod"])
c_cutoff

#get all the pair eqtl marker and gene from b and c
bc_pair <- rbind(b[,c("genes","eqtl_marker")],c[,c("genes","eqtl_marker")])
bc_pair$genes <- as.character(bc_pair$genes)
bc_pair <- bc_pair[!duplicated(bc_pair[,1:2]),]

#extract from b and c respectively
# load("output/gbrs358.eqtl.RData")
# bc_pair_b_lod <- bc_pair
# bc_pair_b_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_b_lod$g <- "GBRS"
load("output/bc_pair_b_lod_gbrs358.RData")

# load("output/fixed.gigamuga358.eqtl.RData")
# bc_pair_c_lod <- bc_pair
# bc_pair_c_lod$lod <- as.vector(unlist(mclapply(X = 1:nrow(bc_pair),
#                                              FUN = function(i){eqtl[as.character(bc_pair[i,2]),as.character(bc_pair[i,1])]},
#                                              mc.cores = 20,
#                                              mc.preschedule = F)))
# bc_pair_c_lod$g <- "FIXED.GIGAMUGA"
load("output/bc_pair_c_lod_fixed.gigamuga358.RData")

bc_pair_lod3 <- merge(bc_pair_b_lod, bc_pair_c_lod, by = c("eqtl_marker", "genes"))
bc_pair_lod3$g <- ifelse(bc_pair_lod3$lod.x >= b_cutoff & bc_pair_lod3$lod.y >= c_cutoff, "Both", ifelse(bc_pair_lod3$lod.x >= b_cutoff & bc_pair_lod3$lod.y < c_cutoff,"GBRS","FIXED.GIGAMUGA"))
#scatter plot for the overlapped genes between GBRS and FIXED.GIGAMUGA
# scatter plot
plot_bcpair_lod1 <- plot_ly(bc_pair_lod3, x = ~lod.x) %>%
  add_markers(y = ~lod.y, text = bc_pair_lod3$eqtl_marker, name = "", showlegend = FALSE) %>%
  add_lines(y = ~fitted(loess(lod.y ~ lod.x)),
            line = list(color = 'black'),
            name = "", showlegend = FALSE) %>%
  add_lines(y = ~lod.x, color = I("red"), name = "", showlegend = FALSE) %>%
  layout(xaxis = list(title = 'LODs in GBRS'),
         yaxis = list(title = 'LODs in FIXED.GIGAMUGA'),
         title = paste0('Scatter plot of LODs for distal eQTLs in identified in either array or GBRS'))

plot_bcpair_lod1


bc_pair_lod3$density <- get_density(bc_pair_lod3$lod.x, bc_pair_lod3$lod.y, n = 100)
plot_bcpair_lod23 <- ggplot(bc_pair_lod3) + 
  geom_point(aes(lod.x, lod.y, color = factor(bc_pair_lod3$g))) + 
  #scale_color_viridis() + 
  theme(aspect.ratio=1) +
  xlab("LODs in GBRS") +
  ylab("LOD in FIXED.GIGAMUGA") +
  ggtitle("Scatter plot of LODs for distal eQTLs in identified in either array or GBRS") + 
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(legend.title=element_blank(), text = element_text(size=22), 
        axis.title=element_text(size=22,face="bold")) +
  theme(plot.title = element_text(hjust=0.5, size = 28))

plot_bcpair_lod23

```

# New Figure 3 Scatterplot for Trans-eQTL at FDR 0.05 (5 Mb)
```{r New Figure 3 Scatterplot for Trans-eQTL at FDR 0.05 (5 Mb), message=FALSE, eval=TRUE,fig.height=16, fig.width=16}
plot_bcpair1 <- ggplot(bc_pair_lod1) + 
  geom_point(aes(lod.x, lod.y, 
                 color = factor(bc_pair_lod1$g)), 
             size = 0.5) + 
  scale_color_manual(values=c("red",
                              "#FDE725FF", 
                              "#404788FF")) +
  theme(aspect.ratio=1) +
  xlab("") +
  ylab("Trans-eQTL LOD in FIXED.MUGA") +
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.title=element_blank(), 
        text = element_text(size=12),
        axis.title.x=element_blank(),
        strip.text.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        axis.title=element_text(size=12))
plot_bcpair1

plot_bcpair2 <- ggplot(bc_pair_lod2) + 
  geom_point(aes(lod.x, lod.y, 
                 color = factor(bc_pair_lod2$g)), 
             size = 0.5) + 
  scale_color_manual(values=c("red",
                              "#55C667FF", 
                              "#404788FF")) +
  theme(aspect.ratio=1) +
  xlab("") +
  ylab("Trans-eQTL LOD in FIXED.MEGAMUGA") +
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.title=element_blank(), 
        text = element_text(size=12), 
        axis.title.x=element_blank(),
        strip.text.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        axis.title=element_text(size=12))
plot_bcpair2

plot_bcpair3 <- ggplot(bc_pair_lod3) + 
  geom_point(aes(lod.x, lod.y, 
                 color = factor(bc_pair_lod3$g)), 
             size = 0.5) + 
  scale_color_manual(values=c("red",
                              "#238A8DFF", 
                              "#404788FF")) +
  theme(aspect.ratio=1) +
  xlab("Trans-eQTL LOD in GBRS") +
  ylab("Trans-eQTL LOD in FIXED.GIGAMUGA") +
  scale_y_continuous(limits=c(0, 180)) +
  scale_x_continuous(limits=c(0, 180)) +
  theme(legend.position="none") +
  geom_abline(slope=1, intercept=0) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.title=element_blank(), 
        text = element_text(size=12), 
        strip.text.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"),
        axis.title=element_text(size=12))
plot_bcpair3

plot_bcpair_row <- plot_grid(plot_bcpair1,
                         plot_bcpair2,
                         plot_bcpair3, 
                        labels = c("A", "B", "C"), 
                        align = "hv",nrow = 1, ncol = 3, vjust = 10)

ggsave("output/Figure4_row.pdf", plot_bcpair_row, height = 8, width=14)


plot_bcpair_col <- plot_grid(plot_bcpair1,
                         plot_bcpair2,
                         plot_bcpair3, 
                        labels = c("A", "B", "C"), hjust = -22,
                        align = "hv",nrow = 3)

ggsave("output/Figure4_col.pdf", plot_bcpair_col, height = 12, width=10)

```

