---
title: "Figure3"
author: "Hao He"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  toc: true
vignette: >
  %\VignetteIndexEntry{Figure3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE)
```

# Figure 3
a) Maybe just one plot with the curves of GBRS (sigma=0.130), Muga, Megamuga, and Gigamuga including both before/after correction of sample mixups. 
Because combining results did not make the result better, let’s ditch it.

# Figure 3, Cis-eQTL
```{r Figure 3 Cis-eQTL, message=FALSE, eval=TRUE, fig.height=20, fig.width=20}
library(sinaplot)
library(ggplot2)
library(plyr)
library(VennDiagram)
library(dplyr)
library(data.table)
library(qvalue)
library(gridExtra)

#eqtl results with generation -----------------------------------------------------------------
#load cis-eqtl
##meta data
meta.data <- c("muga275", "gbrs275", "fixed.muga275",
               "megamuga184","gbrs184","fixed.megamuga184",
               "gigamuga358","gbrs358","fixed.gigamuga358")

mainDir <- "/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/"

cis.eqtl.total <- list()
cislod.plot <- list()
for (i in meta.data){
  cis.eqtl.total[[i]] <- get(load(paste0(mainDir,i,"/",i,"_cis.eqtl.RData")))
  # quantile and combine cisqtl
  cislod.plot[[i]]$array = rep(i,100)
  cislod.plot[[i]]$sub.array = rep(i,100)
  cislod.plot[[i]]$qgrid = seq(from=0.70, to=0.999, length=100)
  cislod.plot[[i]]$quantile.cislod <- quantile(cis.eqtl.total[[i]]$cislod[!is.nan(cis.eqtl.total[[i]]$cislod)],
                      seq(from=0.70, to=0.999, length=100))
  }
cislod.plot.data <- do.call(rbind.data.frame, cislod.plot)
cislod.plot.data$array <- ordered(cislod.plot.data$array, 
                                  levels = c("muga275", "gbrs275", "fixed.muga275",
                                             "megamuga184","gbrs184","fixed.megamuga184",
                                             "gigamuga358","gbrs358","fixed.gigamuga358"))
cislod.plot.data$sub.array <- ordered(cislod.plot.data$sub.array, 
                                  levels = c("muga275", "gbrs275", "fixed.muga275",
                                             "megamuga184","gbrs184","fixed.megamuga184",
                                             "gigamuga358","gbrs358","fixed.gigamuga358"))

#revalue 
cislod.plot.data$array <- revalue(cislod.plot.data$array, c("muga275" = "MUGA", 
                                  "gbrs275" = "MUGA", 
                                  "fixed.muga275" = "MUGA",
                                  "megamuga184" = "MEGAMUGA",
                                  "gbrs184" = "MEGAMUGA",
                                  "fixed.megamuga184" = "MEGAMUGA",
                                  "gigamuga358" = "GIGAMUGA",
                                  "gbrs358" = "GIGAMUGA",
                                  "fixed.gigamuga358" = "GIGAMUGA"))

#revalue 
cislod.plot.data$sub.array <- revalue(cislod.plot.data$sub.array, c("muga275" = "MUGA", 
                                  "gbrs275" = "GBRS.MUGA", 
                                  "fixed.muga275" = "FIXED.MUGA",
                                  "megamuga184" = "MEGAMUGA",
                                  "gbrs184" = "GBRS.MEGAMUGA",
                                  "fixed.megamuga184" = "FIXED.MEGAMUGA",
                                  "gigamuga358" = "GIGAMUGA",
                                  "gbrs358" = "GBRS.GIGAMUGA",
                                  "fixed.gigamuga358" = "FIXED.GIGAMUGA"))

# plot
# GBRS <- "red",
# MUGA <- "cyan",
# MEGAMUGA <- "blue",
# GIGAMUGA <- "green3"
p <- ggplot(data=cislod.plot.data, aes(x=qgrid, y = quantile.cislod)) + 
  geom_line(aes(linetype=sub.array,color=sub.array), size = 1) +
  scale_color_manual(values=c("cyan","cyan", "cyan", "blue", "blue", "blue", "green3","green3","green3")) +
  scale_linetype_manual(values= rep(c("dashed","solid","twodash"), times = 3))+
  xlab("Quantile of LODs") +
  ylab("LOD of cis-eQTL") +
  ggtitle("Cis-eQTL with generation") + 
  #scale_y_continuous(limits=c(0, 120)) +
  theme(legend.title=element_blank(), legend.text=element_text(size=20), plot.title = element_text(size = 30, face = "bold")) +
  theme(axis.text=element_text(size=20),axis.title=element_text(size=20,face="bold"))
p

p <- ggplot(data=cislod.plot.data, aes(x=qgrid, y = quantile.cislod)) + 
  geom_line(aes(linetype=sub.array,color=sub.array), size = 1) +
  scale_color_manual(values=c("cyan","cyan", "cyan", "blue", "blue", "blue", "green3","green3","green3")) +
  scale_linetype_manual(values= rep(c("dashed","solid","twodash"), times = 3))+
  xlab("Quantile of LODs") +
  ylab("LOD of cis-eQTL") +
  ggtitle("Cis-eQTL with generation") + 
  #scale_y_continuous(limits=c(0, 120)) +
  theme(legend.title=element_blank(), legend.text=element_text(size=20), plot.title = element_text(size = 30, face = "bold")) +
  theme(axis.text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
        strip.text = element_text(size = 20)) +
  facet_grid(array ~ ., scales="free", space="free")
#facet_grid(.~array, scales="free", space="free")
p
```

# Figure 3 Trans-eQTL at FDR 0.05 (5 Mb)
```{r Figure 3 Trans-eQTL at FDR 0.05 5Mb, message=FALSE, eval=TRUE,fig.height=16, fig.width=16}
a1 = a2 = a3 = n12 = n13 = n23 = n123 = list()
load("/projects/heh/HH/GBRS_array/data/gene.anno.cis.RData")
#load eqtl pvalue for muga275
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/muga275/muga275_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",a$pos)
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs275/gbrs275_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",b$pos)
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.muga275/fixed.muga275_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",c$pos)
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(b$genes)), 
                             table(ab$trans_agree)[[1]], 
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(c$genes)), 
                             table(ac$trans_agree)[[1]], 
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                             length(unique(c$genes)), 
                             table(bc$trans_agree)[[1]], 
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(b$genes)), 
                             table(ab$trans_agree)[[1]], 
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(c$genes)), 
                             table(ac$trans_agree)[[1]], 
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                             length(unique(c$genes)), 
                             table(bc$trans_agree)[[1]], 
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[1]] = length(unique(a$marker))
a2[[1]] = length(unique(b$marker))
a3[[1]] = length(unique(c$marker))
n12[[1]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[1]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[1]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[1]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

#load eqtl pvalue for megamuga184
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/megamuga184/megamuga184_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",a$pos)
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs184/gbrs184_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",b$pos)
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.megamuga184/fixed.megamuga184_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",c$pos)
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[2]] = length(unique(a$marker))
a2[[2]] = length(unique(b$marker))
a3[[2]] = length(unique(c$marker))
n12[[2]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[2]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[2]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[2]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

#load eqtl pvalue for gigamuga358
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gigamuga358/gigamuga358_pvalue.RData"))
a <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
a$marker <- paste0(a$chr,"_",a$pos)
a$max_qvalue <- qvalue(p = a$pval)$qvalues
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$max_qvalue <= 0.05 & a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs358/gbrs358_pvalue.RData"))
b <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
b$marker <- paste0(b$chr,"_",b$pos)
b$max_qvalue <- qvalue(p = b$pval)$qvalues
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$max_qvalue <= 0.05 & b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.gigamuga358/fixed.gigamuga358_pvalue.RData"))
c <- setDT(pvalue)[, .SD[which.max(lod)], by=genes]
c$marker <- paste0(c$chr,"_",c$pos)
c$max_qvalue <- qvalue(p = c$pval)$qvalues
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$max_qvalue <= 0.05 & c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[3]] = length(unique(a$marker))
a2[[3]] = length(unique(b$marker))
a3[[3]] = length(unique(c$marker))
n12[[3]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[3]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[3]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[3]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

save(a1,a2,a3,n12, n13, n23, n123, file = "/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/venn_diag_transeqtl_max.RData")

load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/venn_diag_transeqtl_max.RData")
#bar plot
barplot(c(a3[[1]],a3[[2]],a3[[3]]),
        ylab = "Number of trans-eQTL at FDR 0.05",
        names.arg = c("FIXED.MUGA", "FIXED.MEGAMUGA", "FIXED.GIGAMUGA"), font.axis = 4, las = 1,cex.names=1.5,cex.lab = 1.5,
        col = c("cyan", "blue", "green3"),
        ylim = c(0,2500))

#MUGA
g1 <- draw.triple.venn(area1 = a1[[1]], 
                 area2 = a2[[1]], 
                 area3 = a3[[1]], 
                 n12 = n12[[1]], 
                 n23 = n23[[1]], 
                 n13 = n13[[1]], 
                 n123 = n123[[1]], 
                 category = c("MUGA", "GBRS", "FIXED.MUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#MEGAMUGA
g2 <- draw.triple.venn(area1 = a1[[2]], 
                 area2 = a2[[2]], 
                 area3 = a3[[2]], 
                 n12 = n12[[2]], 
                 n23 = n23[[2]], 
                 n13 = n13[[2]], 
                 n123 = n123[[2]], 
                 category = c("MEGAMUGA", "GBRS", "FIXED.MEGAMUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#GIGAMUGA
g3 <-  draw.triple.venn(area1 = a1[[3]], 
                 area2 = a2[[3]], 
                 area3 = a3[[3]], 
                 n12 = n12[[3]], 
                 n23 = n23[[3]], 
                 n13 = n13[[3]], 
                 n123 = n123[[3]], 
                 category = c("GIGAMUGA", "GBRS", "FIXED.GIGAMUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#three venn diagrams
grid.arrange(gTree(children=g1),
             top=textGrob("Venn diagram for number of distal eQTLs (5Mb) between array and GBRS", gp=gpar(fontsize=26,font=8)))

grid.arrange(gTree(children=g2))

grid.arrange(gTree(children=g3))

```

# Figure 3 Trans-eQTL at LOD >=8 (5 Mb)
```{r Figure 3 Trans-eQTL at LOD 8 5Mb, message=FALSE, eval=TRUE,fig.height=16, fig.width=16}
a1 = a2 = a3 = n12 = n13 = n23 = n123 = list()
load("/projects/heh/HH/GBRS_array/data/gene.anno.cis.RData")
#load eqtl pvalue for muga275
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/muga275/muga275_pvalue.RData"))
a <- a[a$lod >= 8,]
a$marker <- paste0(a$chr,"_",a$pos)
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs275/gbrs275_pvalue.RData"))
b <- b[b$lod >= 8,]
b$marker <- paste0(b$chr,"_",b$pos)
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.muga275/fixed.muga275_pvalue.RData"))
c <- c[c$lod >= 8,]
c$marker <- paste0(c$chr,"_",c$pos)
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(b$genes)), 
                             table(ab$trans_agree)[[1]], 
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(c$genes)), 
                             table(ac$trans_agree)[[1]], 
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                             length(unique(c$genes)), 
                             table(bc$trans_agree)[[1]], 
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(b$genes)), 
                             table(ab$trans_agree)[[1]], 
                             category = c("MUGA", "GBRS"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "pink1"),
                             ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                             length(unique(c$genes)), 
                             table(ac$trans_agree)[[1]], 
                             category = c("MUGA", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("skyblue", "mediumorchid"),
                             ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                             length(unique(c$genes)), 
                             table(bc$trans_agree)[[1]], 
                             category = c("GBRS", "FIXED.MUGA"),
                             lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                             cat.pos = c(0, 0),
                             fill = c("pink1", "mediumorchid"),
                             ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                   label = c("1",
                             paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                             paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                             "1",
                             paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                             "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  scale_y_discrete(labels=c("a" = "MUGA", "b" = "GBRS","c" = "FIXED.MUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[1]] = length(unique(a$marker))
a2[[1]] = length(unique(b$marker))
a3[[1]] = length(unique(c$marker))
n12[[1]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[1]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[1]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[1]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

#load eqtl pvalue for megamuga184
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/megamuga184/megamuga184_pvalue.RData"))
a <- a[a$lod >= 8,]
a$marker <- paste0(a$chr,"_",a$pos)
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs184/gbrs184_pvalue.RData"))
b <- b[b$lod >= 8,]
b$marker <- paste0(b$chr,"_",b$pos)
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.megamuga184/fixed.megamuga184_pvalue.RData"))
c <- c[c$lod >= 8,]
c$marker <- paste0(c$chr,"_",c$pos)
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("MEGAMUGA", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.MEGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  scale_y_discrete(labels=c("a" = "MEGAMUGA", "b" = "GBRS","c" = "FIXED.MEGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[2]] = length(unique(a$marker))
a2[[2]] = length(unique(b$marker))
a3[[2]] = length(unique(c$marker))
n12[[2]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[2]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[2]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[2]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

#load eqtl pvalue for gigamuga358
a <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gigamuga358/gigamuga358_pvalue.RData"))
a <- a[a$lod >= 8,]
a$marker <- paste0(a$chr,"_",a$pos)
a$eqtl_marker <- paste0(a$chr, "_", a$pos)
a <- merge(a, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
a$cis_trans <- ifelse((a$chr.y == a$chr.x) & (abs(a$pos - a$start) <= 5e+06),"cis", "trans")
a <- a[a$cis_trans == "trans",]

b <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/gbrs358/gbrs358_pvalue.RData"))
b <- b[b$lod >= 8,]
b$marker <- paste0(b$chr,"_",b$pos)
b$eqtl_marker <- paste0(b$chr, "_", b$pos)
b <- merge(b, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
b$cis_trans <- ifelse((b$chr.y == b$chr.x) & (abs(b$pos - b$start) <= 5e+06),"cis", "trans")
b <- b[b$cis_trans == "trans",]

c <- get(load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/analysis/eqtl_with_perms/fixed.gigamuga358/fixed.gigamuga358_pvalue.RData"))
c <- c[c$lod >= 8,]
c$marker <- paste0(c$chr,"_",c$pos)
c$eqtl_marker <- paste0(c$chr, "_", c$pos)
c <- merge(c, gene.anno, by.x=c("genes"), by.y=c("gene"), all.x = TRUE)
c$cis_trans <- ifelse((c$chr.y == c$chr.x) & (abs(c$pos - c$start) <= 5e+06),"cis", "trans")
c <- c[c$cis_trans == "trans",]

p1 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 2e+06),
  "agree",
  "disagree"
)
#pairwise venn
p1[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp1 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (2Mb)")

p2 <- list()
#a and b
ab <- merge(a, b, by = "genes")
ab$trans_agree <- ifelse(
  (ab$chr.x.x == ab$chr.x.y) & (abs(ab$pos.x - ab$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[1]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(b$genes)), 
                              table(ab$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "GBRS"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "pink1"),
                              ind = FALSE)

#a and c
ac <- merge(a, c, by = "genes")
ac$trans_agree <- ifelse(
  (ac$chr.x.x == ac$chr.x.y) & (abs(ac$pos.x - ac$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[2]] <- draw.pairwise.venn(length(unique(a$genes)), 
                              length(unique(c$genes)), 
                              table(ac$trans_agree)[[1]], 
                              category = c("GIGAMUGA", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("skyblue", "mediumorchid"),
                              ind = FALSE)

#b and c
bc <- merge(b, c, by = "genes")
bc$trans_agree <- ifelse(
  (bc$chr.x.x == bc$chr.x.y) & (abs(bc$pos.x - bc$pos.y) <= 5e+06),
  "agree",
  "disagree"
)
#pairwise venn
p2[[3]] <- draw.pairwise.venn(length(unique(b$genes)), 
                              length(unique(c$genes)), 
                              table(bc$trans_agree)[[1]], 
                              category = c("GBRS", "FIXED.GIGAMUGA"),
                              lty = rep("blank", 1), cex= rep(2, 3), cat.cex = rep(1.5,2), 
                              cat.pos = c(0, 0),
                              fill = c("pink1", "mediumorchid"),
                              ind = FALSE)

#show in a triangle
df_long <- data.frame(v1 = factor(c("a","a","a","b","b","c")),
                      v2 = factor(c("a","b","c","b","c","c")),
                      v3 = c(1,
                             table(ab$trans_agree)[[1]]/nrow(ab),
                             table(ac$trans_agree)[[1]]/nrow(ac),
                             1,
                             table(bc$trans_agree)[[1]]/nrow(bc),
                             1),
                      label = c("1",
                                paste0(round(table(ab$trans_agree)[[1]]/nrow(ab),3), "\n",table(ab$trans_agree)[[1]], "/",nrow(ab)),
                                paste0(round(table(ac$trans_agree)[[1]]/nrow(ac),3), "\n",table(ac$trans_agree)[[1]], "/",nrow(ac)),
                                "1",
                                paste0(round(table(bc$trans_agree)[[1]]/nrow(bc),3), "\n",table(bc$trans_agree)[[1]], "/",nrow(bc)),
                                "1"))
pp2 <- ggplot(df_long, aes(x = v1, y = v2, fill = v3)) +
  geom_raster() +
  geom_text(aes(label = label), size = 6) +
  scale_fill_distiller(palette = "Spectral") +
  theme_minimal() +
  theme(legend.position="none",
        panel.grid = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(), text = element_text(size=20)) +
  scale_x_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  scale_y_discrete(labels=c("a" = "GIGAMUGA", "b" = "GBRS","c" = "FIXED.GIGAMUGA")) +
  labs(title="Calling agreement of distal eQTLs between array and GBRS (5Mb)")

#triangle plot
grid.arrange(pp1, pp2, nrow = 2)

#three venn diagrams
grid.arrange(gTree(children=p1[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (2Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p1[[2]]))
grid.arrange(gTree(children=p1[[3]]))

#three venn diagrams
grid.arrange(gTree(children=p2[[1]]),
             top=textGrob("Venn diagram for number of distal eQTLs in agreement between array and GBRS (5Mb)", gp=gpar(fontsize=26,font=8)))
grid.arrange(gTree(children=p2[[2]]))
grid.arrange(gTree(children=p2[[3]]))

a1[[3]] = length(unique(a$marker))
a2[[3]] = length(unique(b$marker))
a3[[3]] = length(unique(c$marker))
n12[[3]] <- length(intersect(unique(a$marker), unique(b$marker)))
n13[[3]] <- length(intersect(unique(a$marker), unique(c$marker)))
n23[[3]] <- length(intersect(unique(b$marker), unique(c$marker)))
n123[[3]] = length(intersect(unique(a$marker),intersect(unique(b$marker), unique(c$marker))))

save(a1,a2,a3,n12, n13, n23, n123, file = "/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/venn_diag_transeqtl_max.RData")

load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/venn_diag_transeqtl_max.RData")
#bar plot
barplot(c(a3[[1]],a3[[2]],a3[[3]]),
        ylab = "Number of trans-eQTL at FDR 0.05",
        names.arg = c("FIXED.MUGA", "FIXED.MEGAMUGA", "FIXED.GIGAMUGA"), font.axis = 4, las = 1,cex.names=1.5,cex.lab = 1.5,
        col = c("cyan", "blue", "green3"),
        ylim = c(0,2500))

#MUGA
g1 <- draw.triple.venn(area1 = a1[[1]], 
                 area2 = a2[[1]], 
                 area3 = a3[[1]], 
                 n12 = n12[[1]], 
                 n23 = n23[[1]], 
                 n13 = n13[[1]], 
                 n123 = n123[[1]], 
                 category = c("MUGA", "GBRS", "FIXED.MUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#MEGAMUGA
g2 <- draw.triple.venn(area1 = a1[[2]], 
                 area2 = a2[[2]], 
                 area3 = a3[[2]], 
                 n12 = n12[[2]], 
                 n23 = n23[[2]], 
                 n13 = n13[[2]], 
                 n123 = n123[[2]], 
                 category = c("MEGAMUGA", "GBRS", "FIXED.MEGAMUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#GIGAMUGA
g3 <-  draw.triple.venn(area1 = a1[[3]], 
                 area2 = a2[[3]], 
                 area3 = a3[[3]], 
                 n12 = n12[[3]], 
                 n23 = n23[[3]], 
                 n13 = n13[[3]], 
                 n123 = n123[[3]], 
                 category = c("GIGAMUGA", "GBRS", "FIXED.GIGAMUGA"), lty = "blank", 
                 cex= rep(2, 7), cat.cex = rep(2,3), ind = FALSE,
                 fill = c("skyblue", "pink1", "mediumorchid"))

#three venn diagrams
grid.arrange(gTree(children=g1),
             top=textGrob("Venn diagram for number of distal eQTLs (5Mb) between array and GBRS", gp=gpar(fontsize=26,font=8)))

grid.arrange(gTree(children=g2))

grid.arrange(gTree(children=g3))

```
