---
title: "recombinations"
author: "Hao He"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  toc: true
vignette: >
  %\VignetteIndexEntry{recombinations_in_DO_Liver_MUGA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE)
```

```{r load_packages, include=FALSE}
library(reticulate)
library(abind)
library(qtl2)
library(ggplot2)
library(DOQTL)
library(gridExtra)
library(VennDiagram)
library(foreach)
library(doParallel)
library(parallel)
library(plyr)
library(DT)

# GET EQUATION AND R-SQUARED AS STRING
# SOURCE: http://goo.gl/K4yh

lm_eqn <- function(df){
    m <- lm(y ~ x, df);
    eq <- substitute(italic(y) == a + b %.% italic(x), 
         list(a = format(coef(m)[1], digits = 2), 
              b = format(coef(m)[2], digits = 2)))
    as.character(as.expression(eq));                 
}

```

# Recombination comparsion between MUGA282 and GBRS282 (Genoprobs)
```{r Recombination comparsion between MUGA282 and GBRS282 (Genoprobs), message=FALSE, eval=TRUE, fig.height=20, fig.width=20}
#sample sheet
sample.sheet <- read.table("/projects/heh/HH/GBRS_array/data/DO_Liver/sample_sheet.tsv", header = TRUE)
#muga282
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/muga282.recomb.RData")
#add gen
#merge with sample sheet
recomb.muga.plot <- merge(muga282.recomb, sample.sheet, by = "Sample", all.x = TRUE)
recomb.muga.plot$Gen <- as.factor(recomb.muga.plot$Gen)
#get summary table for each generation
summary.muga.recomb <- ddply(recomb.muga.plot,.(Gen),
                           summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
#display summary table summary.muga.recomb
DT::datatable(summary.muga.recomb,options = list(pageLength = 20, scrollY = "100px", scrollX = "20px"))
#boxplot
p1 <-ggplot(recomb.muga.plot, aes(x = Gen, y = recomb)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
  theme(legend.position="none") +
  geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
  geom_text(x = 2, y = 700, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.muga.plot$recomb, x = recomb.muga.plot$Gen)), parse = TRUE) +
  labs(x = "DO Outbreeding Generations") +
  labs(y = "Number of Recombinations (MUGA)") +
  scale_x_discrete(limits=c("4","5","6","7")) +
  ylim(100, 700) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
print(p1)

#gbrs282
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/GBRS282.recomb.RData")
sigma = c("0.110", "0.115", "0.120", "0.125", "0.130")
p <- list()
summary.GBRS.recomb <- list()
for (sg in sigma){
  #merge with sample sheet
  recomb.GBRS.plot <- merge(GBRS282.recomb[[sg]], sample.sheet, by = "Sample", all.x = TRUE)
  recomb.GBRS.plot$Gen <- as.factor(recomb.GBRS.plot$Gen)
  #get summary table for each generation per sigma value
  summary.GBRS.recomb[[sg]] <- ddply(recomb.GBRS.plot,.(Gen),
                           summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
  summary.GBRS.recomb[[sg]]$sigma <- sg
  #boxplot
  p[[sg]]<- ggplot(recomb.GBRS.plot, aes(x = Gen, y = recomb)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
    theme(legend.position="none") +
    geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
    geom_text(x = 2, y = 600, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.GBRS.plot$recomb, x = recomb.GBRS.plot$Gen)), parse = TRUE) +
    labs(x = "DO Outbreeding Generations") +
    labs(y = paste0("Number of Recombinations (GBRS,sigma =", sg, "), (Genoprobs)")) +
    scale_x_discrete(limits=c("4","5","6","7")) +
    ylim(100, 600) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
  print(p[[sg]])
}
#plot between GBRS and MUGA
grid.arrange(p1,p[[1]],p[[2]],p[[3]],p[[4]],p[[5]], ncol=6,top = textGrob("Recombination events between GBRS and MUGA",gp=gpar(fontsize=14,font=2)))
#get summary table for GBRS
summary.GBRS.recomb <- do.call(rbind.data.frame,summary.GBRS.recomb)
rownames(summary.GBRS.recomb) <- NULL
#display summary table summary.GBRS.recomb
DT::datatable(summary.GBRS.recomb,options = list(pageLength = 100, scrollY = "800px", scrollX = "20px"))
```

# Recombination GBRS282 (Genotypes)
```{r Recombination GBRS282 (Genotypes), message=FALSE, eval=TRUE, fig.height=20, fig.width=20}
load("./output/DO_Liver/recomb.GBRS.genotypes.RData")
#muga282
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/muga282.recomb.RData")
#sample sheet
sample.sheet <- read.table("/projects/heh/HH/GBRS_array/data/DO_Liver/sample_sheet.tsv", header = TRUE)
#subset sample sheet to 282 samples
sample.sheet <- sample.sheet[sample.sheet$Sample %in% muga282.recomb$Sample,]
sigma = c("0.110", "0.115", "0.120", "0.125", "0.130")
#get summary table for each generation per sigma value
summary.tab <- list()
p <- list()
for (sg in sigma){
  print(sg)
  #merge with sample sheet
  recomb.GBRS.genotypes.plot <- merge(recomb.GBRS.genotypes[[sg]], sample.sheet, by = "Sample", all.y = TRUE)
  recomb.GBRS.genotypes.plot$Gen <- as.factor(recomb.GBRS.genotypes.plot$Gen)
  #get summary table for each generation per sigma value
  summary.tab[[sg]] <- ddply(recomb.GBRS.genotypes.plot,.(Gen),
                summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
  summary.tab[[sg]]$sigma <- sg
  
  #boxplot
  p[[sg]] <-ggplot(recomb.GBRS.genotypes.plot, aes(x = Gen, y = recomb)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
    theme(legend.position="none") +
    geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
    geom_text(x = 2, y = 500, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.GBRS.genotypes.plot$recomb, x = recomb.GBRS.genotypes.plot$Gen)), parse = TRUE) +
    labs(x = "DO Outbreeding Generations") +
    labs(y = paste0("Number of Recombinations (GBRS,sigma =", sg, "), (Genotypes)")) +
    scale_x_discrete(limits=c("4","5","6","7")) +
    theme(plot.title = element_text(hjust = 0.5)) +
    ylim(100, 500) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
  
  print(p[[sg]])
  
}
#plot between GBRS sigmas
grid.arrange(p[[1]],p[[2]],p[[3]],p[[4]],p[[5]], ncol=5,top = textGrob("Recombination events of GBRS282 Genotypes in different sigmas",gp=gpar(fontsize=14,font=2)))

summary.tab.genotype <- do.call(rbind.data.frame,summary.tab)
rownames(summary.tab.genotype) <- NULL
#display summary table
DT::datatable(summary.tab.genotype,options = list(pageLength = 100, scrollY = "800px", scrollX = "20px"))
```

# Recombination comparsion between MEGAMUGA200 and GBRS200 (Genoprobs)
```{r Recombination comparsion between MEGAMUGA200 and GBRS200 (Genoprobs), message=FALSE, eval=TRUE, fig.height=10, fig.width=10}
#sample sheet
sample.sheet <- read.table("/projects/heh/HH/GBRS_array/data/DO_Liver/sample_sheet.tsv", header = TRUE)
#megamuga200
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/megamuga200.recomb.RData")
#add gen
#merge with sample sheet
recomb.muga.plot <- merge(megamuga200.recomb, sample.sheet, by = "Sample", all.x = TRUE)
recomb.muga.plot$Gen <- as.factor(recomb.muga.plot$Gen)
#get summary table for each generation
summary.muga.recomb <- ddply(recomb.muga.plot,.(Gen),
                           summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
#display summary table summary.muga.recomb
DT::datatable(summary.muga.recomb,options = list(pageLength = 20, scrollY = "100px", scrollX = "20px"))
#boxplot
p1 <-ggplot(recomb.muga.plot, aes(x = Gen, y = recomb)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
  theme(legend.position="none") +
  geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
  geom_text(x = 2, y = 1500, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.muga.plot$recomb, x = recomb.muga.plot$Gen)),
            parse = TRUE) +
  labs(x = "DO Outbreeding Generations") +
  labs(y = paste0("Number of Recombinations (MEGAMUGA)")) +
  scale_x_discrete(limits=c("4","7","11")) +
  #ylim(100, 700) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
print(p1)

# two samples with crazy recombinations > 600
#merge with sample sheet
recomb.muga.plot <- recomb.muga.plot[recomb.muga.plot$recomb < 600,]
#get summary table for each generation
summary.muga.recomb <- ddply(recomb.muga.plot,.(Gen),
                           summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
#display summary table summary.muga.recomb
DT::datatable(summary.muga.recomb,options = list(pageLength = 20, scrollY = "100px", scrollX = "20px"))
#boxplot
p2 <-ggplot(recomb.muga.plot, aes(x = Gen, y = recomb)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
  theme(legend.position="none") +
  geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
  geom_text(x = 2, y = 700, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.muga.plot$recomb, x = recomb.muga.plot$Gen)),
            parse = TRUE) +
  labs(x = "DO Outbreeding Generations") +
  labs(y = paste0("Number of Recombinations (MEGAMUGA)")) +
  scale_x_discrete(limits=c("4","7","11")) +
  ylim(100, 700) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
print(p2)

#gbrs200
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/GBRS200.recomb.RData")
sigma = c("0.110", "0.115", "0.120", "0.125", "0.130")
p <- list()
summary.GBRS.recomb <- list()
for (sg in sigma){
  #merge with sample sheet
  recomb.GBRS.plot <- merge(GBRS200.recomb[[sg]], sample.sheet, by = "Sample", all.x = TRUE)
  recomb.GBRS.plot$Gen <- as.factor(recomb.GBRS.plot$Gen)
  #get summary table for each generation per sigma value
  summary.GBRS.recomb[[sg]] <- ddply(recomb.GBRS.plot,.(Gen),
                           summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
  summary.GBRS.recomb[[sg]]$sigma <- sg
  #boxplot
  p[[sg]]<- ggplot(recomb.GBRS.plot, aes(x = Gen, y = recomb)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
    theme(legend.position="none") +
    geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
    geom_text(x = 2, y = 700, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.GBRS.plot$recomb, x = recomb.GBRS.plot$Gen)),
            parse = TRUE) +
    labs(x = "DO Outbreeding Generations") +
    labs(y = paste0("Number of Recombinations (GBRS,sigma =", sg, ") (Genoprobs)")) +
    scale_x_discrete(limits=c("4","7","11")) +
    ylim(100, 700) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
  print(p[[sg]])
}
#plot between GBRS and MUGA
grid.arrange(p2,p[[1]],p[[2]],p[[3]],p[[4]],p[[5]], ncol=6,top = textGrob("Recombination events between GBRS and MEGAMUGA",gp=gpar(fontsize=12,font=2)))
#get summary table for GBRS
summary.GBRS.recomb <- do.call(rbind.data.frame,summary.GBRS.recomb)
rownames(summary.GBRS.recomb) <- NULL
#display summary table summary.GBRS.recomb
DT::datatable(summary.GBRS.recomb,options = list(pageLength = 20, scrollY = "800px", scrollX = "20px"))
```

# Recombination GBRS200 (Genotypes)
```{r Recombination GBRS200 (Genotypes), message=FALSE, eval=TRUE, fig.height=10, fig.width=10}
load("./output/DO_Liver/recomb.GBRS.genotypes.RData")
#megamuga200
load("/projects/heh/HH/GBRS_array/Workflowr_Array_GBRS/output/megamuga200.recomb.RData")
#sample sheet
sample.sheet <- read.table("/projects/heh/HH/GBRS_array/data/DO_Liver/sample_sheet.tsv", header = TRUE)
#subset sample sheet to 200 samples
sample.sheet <- sample.sheet[sample.sheet$Sample %in% megamuga200.recomb$Sample,]
sigma = c("0.110", "0.115", "0.120", "0.125", "0.130")
#get summary table for each generation per sigma value
summary.tab <- list()
p <- list()
for (sg in sigma){
  print(sg)
  #merge with sample sheet
  recomb.GBRS.genotypes.plot <- merge(recomb.GBRS.genotypes[[sg]], sample.sheet, by = "Sample", all.y = TRUE)
  recomb.GBRS.genotypes.plot$Gen <- as.factor(recomb.GBRS.genotypes.plot$Gen)
  #get summary table for each generation per sigma value
  summary.tab[[sg]] <- ddply(recomb.GBRS.genotypes.plot,.(Gen),
                summarise,mean = mean(recomb),var = var(recomb), n= length(recomb))
  summary.tab[[sg]]$sigma <- sg
  
  #boxplot
  p[[sg]] <-ggplot(recomb.GBRS.genotypes.plot, aes(x = Gen, y = recomb)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(position = position_jitter(0.25), aes(colour = Gen)) +
    theme(legend.position="none") +
    geom_smooth(method = "lm", se=FALSE, color="black", aes(group=1), linetype="dotted") +
    geom_text(x = 2, y = 600, size = 4, 
            label = lm_eqn(df = data.frame(y = recomb.GBRS.genotypes.plot$recomb, x = recomb.GBRS.genotypes.plot$Gen)), parse = TRUE) +
    labs(x = "DO Outbreeding Generations") +
    labs(y = paste0("Number of Recombinations (GBRS,sigma =", sg, "), (Genotypes)")) +
    scale_x_discrete(limits=c("4","7","11")) +
    theme(plot.title = element_text(hjust = 0.5)) +
    ylim(100, 600) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text=element_text(size=14),axis.title=element_text(size=14,face="bold"))
  
  print(p[[sg]])
  
}
#plot between GBRS sigmas
grid.arrange(p[[1]],p[[2]],p[[3]],p[[4]],p[[5]], ncol=5,top = textGrob("Recombination events of GBRS200 Genotypes in different sigmas",gp=gpar(fontsize=12,font=2)))

summary.tab.genotype <- do.call(rbind.data.frame,summary.tab)
rownames(summary.tab.genotype) <- NULL
#display summary table
DT::datatable(summary.tab.genotype,options = list(pageLength = 100, scrollY = "800px", scrollX = "20px"))
```


